// <auto-generated />
using System;
using CommentHub.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommentHub.Database.Migrations
{
    [DbContext(typeof(CommentHubDbContext))]
    [Migration("20260910203532_AddParentIdRepliesIndex")]
    partial class AddParentIdRepliesIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommentHub.Database.Entities.Attachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("CommentId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("StoragePath")
                        .IsUnique();

                    b.ToTable("Attachments", t =>
                        {
                            t.HasCheckConstraint("CK_Attachments_Dimensions", "(\"Kind\" = 1 AND \"Width\" IS NOT NULL AND \"Width\" <= 320\r\n             AND \"Height\" IS NOT NULL AND \"Height\" <= 240)\r\nOR (\"Kind\" <> 1 AND \"Width\" IS NULL AND \"Height\" IS NULL)");

                            t.HasCheckConstraint("CK_Attachments_SizeBytes_Positive", " \"SizeBytes\" > 0 ");
                        });
                });

            modelBuilder.Entity("CommentHub.Database.Entities.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Depth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RootId")
                        .HasColumnType("bigint");

                    b.Property<string>("TextHtml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RootId");

                    b.HasIndex("UserId");

                    b.HasIndex("CreatedAt", "Id")
                        .IsDescending()
                        .HasDatabaseName("IX_Comments_Roots_CreatedAt_Id")
                        .HasFilter(" \"ParentId\" IS NULL ");

                    b.HasIndex("ParentId", "CreatedAt", "Id")
                        .HasDatabaseName("IX_Comments_Replies_ParentId_CreatedAt_Id")
                        .HasFilter(" \"ParentId\" IS NOT NULL ");

                    b.ToTable("Comments", t =>
                        {
                            t.HasCheckConstraint("CK_Comments_Hierarchy", "(\"ParentId\" IS NULL AND \"RootId\" IS NULL AND \"Depth\" = 0)\r\nOR (\"ParentId\" IS NOT NULL AND \"RootId\" IS NOT NULL AND \"Depth\" > 0)");
                        });
                });

            modelBuilder.Entity("CommentHub.Database.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("HomePage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_UserName_Alphanumeric", " \"UserName\" ~ '^[A-Za-z0-9]+$' ");
                        });
                });

            modelBuilder.Entity("CommentHub.Database.Entities.Attachment", b =>
                {
                    b.HasOne("CommentHub.Database.Entities.Comment", "Comment")
                        .WithMany("Attachments")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("CommentHub.Database.Entities.Comment", b =>
                {
                    b.HasOne("CommentHub.Database.Entities.Comment", "Parent")
                        .WithMany("Replies")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CommentHub.Database.Entities.Comment", "Root")
                        .WithMany()
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CommentHub.Database.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Root");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CommentHub.Database.Entities.Comment", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("CommentHub.Database.Entities.User", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
