<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="HotChocolate.AspNetCore" Version="16.6.4" />
    <PackageReference Include="HotChocolate.Types.Analyzers" Version="16.6.4" PrivateAssets="all" />
    <PackageReference Include="HotChocolate.Data.EntityFramework" Version="16.6.4" />
    <PackageReference Include="HtmlSanitizer" Version="9.2.1039" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommentHub.Database\CommentHub.Database.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Fonts\LiberationSans-Bold.ttf" />
  </ItemGroup>

</Project>
